import EntityNames from "../types/entity-name";

export const pullFromServer: any = {
  products: EntityNames.ProductsPull,
  categories: EntityNames.CategoryPull,
  collections: EntityNames.CollectionPull,
  customers: EntityNames.CustomerPull,
  companies: EntityNames.BusinessDetailsPull,
  locations: EntityNames.BusinessDetailsPull,
  orders: EntityNames.OrdersPull,
  printtemplates: EntityNames.PrintTemplatePull,
  stockhistories: EntityNames.StockHistoryPull,
  batches: EntityNames.BatchPull,
  quickitems: EntityNames.QuickItemsPull,
  charges: EntityNames.CustomChargePull,
  billingSettings: EntityNames.BillingSettingsPull,
  adsManagement: EntityNames.AdsManagementPull,
  sectionTables: EntityNames.SectionTablesPull,
  menu: EntityNames.MenuPull,
  voidComp: EntityNames.VoidCompPull,
  boxCrates: EntityNames.BoxCratesPull,
  menumanagements: EntityNames.MenuPull,
  kitchenmanagements: EntityNames.KitchenManagementPull,
  devices: EntityNames.BillingSettingsPull,
  sections: EntityNames.SectionTablesPull,
  voidcomps: EntityNames.VoidCompPull,
  boxescrates: EntityNames.BoxCratesPull,
  ordernumbersequences: EntityNames.OrderNumberSequencePull,
};
