export type AddProductProps = {
  isRestaurant: boolean;
  isKitchen: boolean;
  en_name: string;
  ar_name: string;
  productPic: string;
  localImage: string;
  kitchenFacingNameEn: string;
  kitchenFacingNameAr: string;
  kitchenRefs: string[];
  kitchens: any[];
  category: { value: string; key: string };
  collectionRefs: string[];
  collections: string[];
  channels: string[];
  selfOrdering: boolean;
  onlineOrdering: boolean;
  description: string;
  brand: { value: string; key: string };
  contains: string;
  tax: { value: string; key: string };
  enabledBatching: boolean;
  bestSeller: boolean;
  type: "single" | "multiple";
  sku: string;
  code: string;
  unit: { value: string; key: string };
  costPrice: string;
  price: string;
  variants: any[];
  actions: any[];
  boxes: any[];
  calorieCount: string;
  preference: string[];
  dietryType: string[];
  modifiers: any[];
  status: string;
  formChanged: boolean;
  stockUpdate: boolean;
};

export type ModalProps = {
  data: any;
  visible: boolean;
  handleClose?: any;
  handleSaveProduct: any;
};
